name: Build and Deploy GitBook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build GitBook
        uses: ZanderZhao/gitbook-action@v1.2.4
        with:
          token: ${{ secrets.GH_TOKEN }}
          source_dir: ./
          gitbook_version: latest
